name: jetleaf_scheduling
description: Task scheduling and timed execution module for the JetLeaf framework.
version: 1.1.4

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_scheduling
issue_tracker: https://github.com/jetleaf/jetleaf_scheduling/issues
documentation: https://jetleaf.hapnium.com/docs/scheduling

topics:
  - scheduling
  - tasks
  - jetleaf
  - async
  - timers

keywords:
  - jetleaf
  - scheduler
  - jobs
  - background
  - timing

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: ^1.1.3
  jetleaf_logging: ^1.1.3
  jetleaf_pod: ^1.1.4
  jetleaf_core: ^1.1.5

dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0